### ISSUE TITLE
iD

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/wikimaps-html#10]
iD just wont fit in the interface, has to be opened in a new window or external.

**Comment by susannaanas** [comment]
We cannot probably stay in sync forever anyway but is there anything we
could change to make them feel more integrated aka where is the problem
specifically?

Susanna

perjantai 10. heinäkuuta 2015 Albin Larsson notifications@github.com
kirjoitti:

**Comment by Abbe98** [comment]
Integrating the left sidebars Wikimaps/iD is a to heavy task and would break future work(making them share sidebar). Having iDs sidebar beside is not a option(have been playing with it).

We could provide "open in iD"/"open in JSOM" buttons, both applications have great APIs for custom layers(used by HOT for example).
