### ISSUE TITLE
Create search UI

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/wikimaps-html#7]
The "Maps" tab needs a UI for it's search.

This could be a overlaying grid or an id-editor like search in the sidebar.

**Comment by susannaanas** [comment]
There is stuff that we have been thinking of. I have made search interface sketches, but they are not really up-to-date. I will find pointers.

Ari just created a maps search proposal, I link it here: https://www.youtube.com/watch?v=A9xiVtHoxpM&feature=youtu.be

**Comment by Abbe98** [comment]
I'm thinking of tome thing like:

![image](https://cloud.githubusercontent.com/assets/2631719/8532374/0353087c-242e-11e5-80d9-1ae9d38f2325.png)

and just having such boxes stacked on each other...

**Comment by susannaanas** [comment]
There is a design for that 
https://photos-1.dropbox.com/t/2/AAB2rwxqxc_Brs9m7OghEvMVpKu4JjZIAa_pA1LYd6OjbQ/12/38234755/png/32x32/1/_/1/2/warper%20-%20view%20-%20toolmenu-top%20-%20hover-01.png/EPKD55gBGLIDIAIoAg/hy1P_Ph0J_rDzGvSbp7QU1K2PoDJxpAmRDVsPLfzmXU?size=800x600&size_mode=2

https://photos-1.dropbox.com/t/2/AACH8Qa7HLw4yT4xih5OrOJiALVJ5ehM9Ke3IFrr8M6QVQ/12/38234755/png/32x32/1/_/1/2/warper%20-%20view%20-%20toolsmenu-01.png/EPKD55gBGLIDIAIoAg/4IrFzmNEgqS9Fk2Jo4vihnIY18-ZUKNbA0CGJHMo5F0?size=800x600&size_mode=2

https://photos-1.dropbox.com/t/2/AAByiAdYAV1snVjaN8fMYMq90EvFqzZjbBRqVaR0TAOitg/12/38234755/png/32x32/1/_/1/2/warper%20-%20view%20-metadata-01.png/EPKD55gBGLIDIAIoAg/dIOhuQTuvK54LxnS0Gg4G58Msi7ZBIprXBfyc3Ccsio?size=800x600&size_mode=2

**Comment by Abbe98** [comment]
:+1:

**Comment by susannaanas** [comment]
I made the basic metadata display into a citation format to save space, instead of a grid of stuff. The upper menu opens a flyout with links to tools. The lower burger opens the full metadata display.

In Ari's example transparency sliders were added and handles for moving around might be needed.

**Comment by Abbe98** [comment]
I think that for search we should display selected meta data inline because no user would leave focus from the search box to click on a burger. It breaks a basic search flow. 

For a selected map we could hide information in such a way or just making the burger expand the "map card" to show more information?

**Comment by susannaanas** [comment]
The burger is meant for expanded metadata view. The essential should be inside. What I collected in the selected metadata, is what can be shown in a library reference: Creator: Map, Publisher, Year. We might want to show something else. too. What do you have in mind?

**Comment by Abbe98** [comment]
I haven't looked into it yet, tomorrow I will be working on minor things in the design, the responsive design and search/controls UI. Then on Wednesday I'm going to play with the existing Warper to get to know the work flow better and start working on more JS/Animation/Help/Meta.

**Comment by susannaanas** [comment]
OK. I will give some input into the map display that will be used all around the site, in search results and as a title to any actions. I will be unavailable for most of the time also.

**Comment by Abbe98** [comment]
Basic setup [link](http://wikimaps-dev.github.io/wikimaps-html/)->maps
