### ISSUE TITLE
Warper login flow

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/wikimaps-html#9]
https://docs.google.com/presentation/d/10ICyB7rHzuQ02QGl65Zcl6I124Mb4HI9ImGjeoa3_xo/edit#slide=id.g55507fafd_0342

**Comment by Abbe98** [comment]
Is alternative logins/register needed?  I think most Wikimaps users would have a Wikimedia account.

**Comment by susannaanas** [comment]
Processing... I think you have a point there. We could assume that the
users should have one of the open project logins, or register to one of
them. The current choise is based on how it was before, and perhaps make it
compatible with the current Warper. Tim, how do you see this?

tiistai 7. heinäkuuta 2015 Albin Larsson notifications@github.com
kirjoitti:
